### ISSUE TITLE
fresh Mycroft install weather spits errors

### ISSUE THREAD

**Issue by Guyverix** [MycroftAI/skill-weather#98] opened 2019-11-06 01:47 UTC
"Whats the weather like?" gives a stack trace on a fresh Mycroft install.  Unfortunately I do not know Python well enough to dig into this..  

How can I get you better / more information to see what the root of this problem is?
My location is: Lake Stevens Wa, USA
from the directory it is residing in, I have the following settings:

cat settings.json 
{"api_key": null, "use_proxy": true, "__mycroft_skill_firstrun": false}

All other skills I have tried (so far) are error free..

The error log is showing this:
`2019-11-05 17:41:52.075 | WARNING  |  4899 | WeatherSkill | No temperature available (AttributeError("'NoneType' object has no attribute 'get_temperature'",))
2019-11-05 17:41:52.076 | WARNING  |  4899 | WeatherSkill | No temperature available (AttributeError("'NoneType' object has no attribute 'get_temperature'",))
2019-11-05 17:41:52.076 | ERROR    |  4899 | WeatherSkill | Error: 'NoneType' object has no attribute 'get_humidity'
Traceback (most recent call last):
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 1230, in __populate_report
    return self.__populate_current(report, when, unit)
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 1309, in __populate_current
    'percentage.number', {'num': forecastWeather.get_humidity()})
AttributeError: 'NoneType' object has no attribute 'get_humidity'
2019-11-05 17:41:52.076 | ERROR    |  4899 | WeatherSkill | Error: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 440, in handle_current_weather
    separate_min_max='Location' not in message.data)
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 1475, in __report_weather
    if report['location']:
TypeError: 'NoneType' object is not subscriptable
`

**Comment by krisgesling** [comment] 2019-11-06 03:31
Hi Guyverix, 

Thanks for flagging this. We are working on a fix now.

It's being caused by the Open Weather Maps API not returning a valid report. So adding some logic to handle these situations and also looking at why the report is not returned properly in the first place.

**Comment by krisgesling** [comment] 2019-11-06 03:31
Hi Guyverix, 

Thanks for flagging this. We are working on a fix now.

It's being caused by the Open Weather Maps API not returning a valid report. So adding some logic to handle these situations and also looking at why the report is not returned properly in the first place.

**Comment by krisgesling** [comment] 2021-06-24 01:53
This should be addressed with the re-write. Closing.

**Closed as completed by krisgesling** 2021-06-24 01:53 UTC
Labels: bug
